apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.fullname" . }}
  annotations:
    getambassador.io/config: |
        ---
        apiVersion: ambassador/v1
        kind:  Mapping
        name:  auth-service-mapping
        prefix: /auth/
        service: auth-service:8080
  labels:
    app.kubernetes.io/name: {{ include "auth-service.name" . }}
    helm.sh/chart: {{ include "auth-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "auth-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
