name: build
on: [push]
jobs:
  build:
    container:
      image: swift:5.1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install SSL dependencies
      run: apt-get -qq update && apt-get install -y libssl-dev libicu-dev zlib1g-dev
    - name: Resolve packages
      run: swift package resolve
    - name: Clean package
      run: swift package clean
    - name: Test
      run: swift test